### PR TITLE
add /fortunes functionality

### PR DESCRIPTION
**Pull request by ianderse**
- Change route to '/fortunes' because Steve is a liar.
- Random fortune is displayed when going to /fortunes

### CODE REVIEW

**Comment by smbsimon** [comment]
Pigeons always deserve the blame. Let's remove that fortune.

**Comment by smbsimon** [comment]
Back over to you, @ianderse.

**Comment by ianderse** [comment]
I disagree, sometimes poop is to blame.

**Comment by ianderse** [comment]
maybe we can blame Steve instead?

**Comment by smbsimon** [comment]
Done.

**Pull request merged**
